services:
  backend:
    build: 
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - labo-network

  postgres:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: labo_221
      POSTGRES_USER: labo_user
      POSTGRES_PASSWORD: labo_password
    ports:
      - '5434:5432'
    volumes:
      - labo_data:/var/lib/postgresql/data
    networks:
      - labo-network

volumes:
  labo_data:

networks:
  labo-network:
    driver: bridge
